name: Auto build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      
      - uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
        
      - name: npm install pnpm
        run: npm install -g pnpm
      
      - name: pnpm install
        run: pnpm install

      - name: Build
        run: pnpm run build
        
      - name: Set up Git
        run: |
          git config --global user.email "18296884762@163.com"
          git config --global user.name "Zgrowth"
  
      - name: Commit changes
        run: |
          git add .
          git commit -m "feat: 构建 by GitHub Actions"
  
      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        run: |
          git push https://x-access-token:${{ secrets.REPO_ACCESS_TOKEN }}@github.com/${{ github.repository }}.git HEAD:master
